apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgadmin

spec:
  rules:
    - host: postgres.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pgadmin
                port:
                  number: 80
